FROM node:lts as build-stage
WORKDIR /app
COPY . .
RUN npm config set strict-ssl false
RUN npm ci --legacy-peer-deps || npm install --legacy-peer-deps
RUN npm run build

FROM nginx:alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
